### ISSUE TITLE
Export to PDF only takes viewport

### ISSUE THREAD

**Issue by johan-steffens** [wnabil/ngx-export-as#1]
Hey man, thanks so much for your library. I do understand that it's still in alpha, but I thought I'd contribute by logging an issue for you.

When I do a PDF export, the resulting PDF only contains whatever's currently visible in the window, not the entire viewport.

For example, my table has a height of 5842 pixels, but my viewport only has a height of 1188 pixels. My resulting PDF doesn't contain the whole table, but only a 1188 pixels high portion of whatever is currently scrolled to in the viewport. The rest is all cut off.

Is there a way to get it to export the whole thing? Maybe a configuration that specifies more pages or something?

**Comment by wnabil** [comment]
Hi, Yeah i faced the same issue before.
Actually it is related to html2canvas library, In order to fix this you can use a css trick:

.html2canvas-container {
  min-height: 670px !important;
}

make sure the min-height is matching your content height, tell me if that works for you please.

**Comment by johan-steffens** [comment]
Thanks for the quick response!

Should I put the CSS in anywhere on my page, or do I need to add the` .html2canvas-container` class to a specific element?

**Comment by wnabil** [comment]
No no just add it anywhere.

**Comment by johan-steffens** [comment]
I put the CSS in the head of my page, but it still cuts off the content like before.

**Comment by wnabil** [comment]
make sure to hot ctrl f5 so the page reload the cached css

**Comment by johan-steffens** [comment]
I've got cachebusting set up on my server, so it auto-versions new CSS files. Regardless, I still did force (Ctrl + F5) refresh, and get the same result.

**Comment by wnabil** [comment]
Ok then please if you can upload an example project and give me the link and i will check it.

**Comment by wnabil** [comment]
NVM i found the issue, please add position: absolute; to your table.

**Comment by johan-steffens** [comment]
I tried position: absolute as well. It still only renders/saves whatever is inside of the current viewport. If you still want me to create an example project just give me some time as the code I'm working on is a bit sensitive and I'll have to strip out the code to provide an example to you.

**Comment by wnabil** [comment]
Okay take your time.
i will response after a while because Friday and Saturday are my weekend.

**Comment by johan-steffens** [comment]
Cool, thanks man!

**Comment by wnabil** [comment]
Hi, i looked into it and yeah i found the same issue, as a temporary solution scroll to the element before exporting it, this allows the element to be visible during the export process.
this way have a problem if your content is too long, i will search on html2canvas library to find a real solution, but you can use this trick to handle it currently.

**Comment by johan-steffens** [comment]
Awesome, glad you could reproduce it. Sorry for not ever coming back to you with an example project; we had some tight deadlines on the project I was working on. We decided to generate the PDF on the server-side and then stream it back to the client-side.

**Comment by wnabil** [comment]
please use v1.2.4
