### ISSUE TITLE
Export to xls format

### ISSUE THREAD

**Issue by bikas-kumar** [wnabil/ngx-export-as#10]
Hi ,

while exporting the table data into excel sheet the table data getting modified automatically.

Ex. Table is having data as '6/7' but in the excel it is coming like '6/7/2001'.

please let me know what is the issue and how i can fix it.

Thanks,
Bikas Kumar

**Comment by wnabil** [comment]
Hi, Please check this related issue.
https://github.com/wnabil/ngx-export-as/issues/8
this issue is related to https://github.com/SheetJS/js-xlsx library
please check the issues in that repo or open a new one for them

**Comment by rajagovindan** [comment]
While exporting the table data to xlsx.. Is there any possible to remove action column???
