### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'colSpan')

### ISSUE THREAD

**Issue by JakobYoo** [wnabil/ngx-export-as#107]
Hello, first of all, great library! Love it!

Today I tried exporting an HTML table to docx and got that error as a response. Sadly I cannot work out, why i get this, especially because the export to xlsx works like a charm. 
This is the table header of the table in question:
![image](https://user-images.githubusercontent.com/9628821/158380364-bbaa0b7d-63a9-42e4-9101-388c6615ee3a.png)

![image](https://user-images.githubusercontent.com/9628821/158380515-302b2052-6cfb-4487-9fc0-888553b13053.png)

If you need anything else, please lmk!
Thanks again!

**Comment by wnabil** [comment]
Please post your deps version
