### ISSUE TITLE
Automatically calculating percentage when exporting table from ngx-export-as in angular

### ISSUE THREAD

**Issue by SupportEtech** [wnabil/ngx-export-as#108]
This is a table view on browser
6 | D Consult/Clinic Contribution % | **63.04%**

but when exporting its showing in excel 
6 | D Consult/Clinic Contribution % | **0.6304**

Please look into it.

**Comment by wnabil** [comment]
Check the options for xls library from the readme file

**Comment by SupportEtech** [comment]
Hello wnabil/ngx-export-as ,Thank you for registering with us.Your account has been setup and you can now login to our client portal . Client portal url : https://etech.vhdin.com/Email: ***@***.*** Please reset your password by using following link https://etech.vhdin.com/?/client/reset_password/cmVwbHkrQVBLRU01SDQ0UFpCUEkyNUM0WTZMNldBTUE2UUpFVkJOSEhFTUNQQzM0QHJlcGx5LmdpdGh1Yi5jb20=/IywzLFkKYAo=Using client portal you can track your existing incidents, submit new incidents and update your profile.

**Comment by SupportEtech** [comment]
Hello wnabil/ngx-export-as ,Thank you for registering with us.Your account has been setup and you can now login to our client portal . Client portal url : https://etech.vhdin.com/Email: ***@***.*** Please reset your password by using following link https://etech.vhdin.com/?/client/reset_password/cmVwbHkrQVBLRU01RzdRNUxSWExMNldWWUE3WTZBTUE2UUhFVkJOSEhFTUNQQzM0QHJlcGx5LmdpdGh1Yi5jb20=/IyxDPFcKYAo=Using client portal you can track your existing incidents, submit new incidents and update your profile.

**Comment by SupportEtech** [comment]
Hello wnabil/ngx-export-as ,           A request for assistance has been received. Our system has created a incident for your issue.Following are incident details -Incident ID: PBMQ-407737Subject: Re: [wnabil/ngx-export-as] Automatically calculating percentage when exporting table from ngx-export-as in angular (Issue #108)Department: E-Tech SupportIncident type: IssuePriority: LowStatus: OpenOur staff will assist you shortly.You can update or reply your incident online at :https://etech.vhdin.com/Login URL  as ***@***.***&vis_salt=eb973f0d40e1a2f8c11b47e55d7ca3bb

**Comment by SupportEtech** [comment]
Hello wnabil/ngx-export-as ,           A request for assistance has been received. Our system has created a incident for your issue.Following are incident details -Incident ID: CRQD-704653Subject: Re: [wnabil/ngx-export-as] Automatically calculating percentage when exporting table from ngx-export-as in angular (Issue #108)Department: E-Tech SupportIncident type: IssuePriority: LowStatus: OpenOur staff will assist you shortly.You can update or reply your incident online at :https://etech.vhdin.com/Login URL  as ***@***.***&vis_salt=3c5f7d6f7c537c79b0d92127b6b045e2
