### ISSUE TITLE
 ngx-export-as to generate PDFs  file has poor resolution

### ISSUE THREAD

**Issue by zeinabsamir** [wnabil/ngx-export-as#11]
![Screenshot from 2019-04-13 19-11-35](https://user-images.githubusercontent.com/15264835/56083112-1de52900-5e21-11e9-9c9e-33d8bb48fb98.png)
Table not showing fully

Hello, I'm using ngx-export-as to generate PDFs however, the generated table in the PDF file has poor resolution and the data is cut off.

Could you help direct me to where I can fix this issue. Thanks!

**Comment by wnabil** [comment]
Hi,
Thanks for reporting, Actually i am planning to fully re-implement the PDF method because currently I am using a PNG image inside the PDF document and i believe this is not the best implementation.
I will try to do that as soon as i have time.

**Comment by wnabil** [comment]
fixed, please use version 1.2.4 and check the readme file for custom quality
