### ISSUE TITLE
Exported CSV displying non-english characters currupted

### ISSUE THREAD

**Issue by ankurkhunt** [wnabil/ngx-export-as#113]
Hi Team,
Hope you are doing well!

Thanks for building this fantastic lib for exporting things easily!

I am facing some issues with non-English characters in the CSV file. I tried various things to convert text into UTF-8 but had no success! Would be great if you can help me to fix the below issue.

I have HTML table which contains these rows

`Test Words
キャンペーン
ハイセンスWチャンス
フォロー
japan
プレゼント
応募受付
テレビ
official
Kチューナー内蔵 液晶
ハイセンス
臨場感
F ネット動画対応
高音質サラウンドシステム
お買い得情報
G ネット動画対応
VAパネル
②告知ツイート
冷凍庫
グローバルブランド
冷蔵庫`

When we export into csv it shows these in Microsoft Excel:
`Test Words
„Ç≠„É£„É≥„Éö„Éº„É≥
„Éè„Ç§„Çª„É≥„ÇπW„ÉÅ„É£„É≥„Çπ
„Éï„Ç©„É≠„Éº
japan
„Éó„É¨„Çº„É≥„Éà
ÂøúÂãüÂèó‰ªò
„ÉÜ„É¨„Éì
official
K„ÉÅ„É•„Éº„Éä„ÉºÂÜÖËîµ Ê∂≤Êô∂
„Éè„Ç§„Çª„É≥„Çπ
Ëá®Â†¥ÊÑü
F „Éç„ÉÉ„ÉàÂãïÁîªÂØæÂøú
È´òÈü≥Ë≥™„Çµ„É©„Ç¶„É≥„Éâ„Ç∑„Çπ„ÉÜ„É†
„ÅäË≤∑„ÅÑÂæóÊÉÖÂ†±
G „Éç„ÉÉ„ÉàÂãïÁîªÂØæÂøú
VA„Éë„Éç„É´
‚ë°ÂëäÁü•„ÉÑ„Ç§„Éº„Éà
ÂÜ∑ÂáçÂ∫´
„Ç∞„É≠„Éº„Éê„É´„Éñ„É©„É≥„Éâ
ÂÜ∑ËîµÂ∫´`

Sample Screenshot:
<img width="851" alt="image" src="https://github.com/wnabil/ngx-export-as/assets/34331536/73de2760-d754-43fe-b524-a761bc9cfddf">

Sample CSV file:
[testCSV.csv](https://github.com/wnabil/ngx-export-as/files/12046151/testCSV.csv)

Thanks!

**Comment by wnabil** [comment]
@ankurkhunt I can see the content of your file correctly without any problems in Visual studio code
![image](https://github.com/wnabil/ngx-export-as/assets/23165327/e50c60f5-cb21-4c2d-9cb2-3632f15ce9fb)
The Excel app configuration is out of this scope, Try playing with the configuration or contact Microsoft support

**Comment by wnabil** [comment]
this is also an online tool for viewing csv files and it works
https://www.convertcsv.com/csv-viewer-editor.htm
![image](https://github.com/wnabil/ngx-export-as/assets/23165327/72faaf5e-2166-44bf-a51e-f20a50412c40)
