### ISSUE TITLE
compatibility with mat-table 

### ISSUE THREAD

**Issue by airasyaqub** [wnabil/ngx-export-as#14]
Hey. So I was going o implement this lib. everything works fine if used native table. I tried to implement it with angular 7 material mat-table and it gives me his error
![error](https://user-images.githubusercontent.com/30695220/57128168-fe03ae00-6dab-11e9-9efb-bea920645e31.PNG)
```
//my config file
private _config: ExportAsConfig = {
    type: 'xlsx',
    elementId: 'table',
 };

// my function

exportAs() {
		this.exportAsService.save(this._config, 'myFile');
		this.exportAsService.get(this._config).subscribe(content => {
	        console.log(content);
	});
}

//<--------in template file---------->
<mat-table id="table" *ngIf="reportByMonthDataSource.length" [dataSource]="reportByMonthDataSource">
 // cotent
</mat-table>
```

What am I doing wrong in here

**Comment by wnabil** [comment]
Hi, Currently this package supports only the normal table element but i think it is possible to implement this feature for you.
Please if you can just upload an example project for me that uses angular material and i will implement it when i have time.

**Comment by wnabil** [comment]
I checked this implementation https://material.angular.io/components/table/overview
I can confirm if you switched your implementation to the official one you will make it work.

use the directives not the direct components so the html table structure will stay the same and the xls library will recognize your table when using table_to_sheet method
