### ISSUE TITLE
supporting arabic language rendering

### ISSUE THREAD

**Issue by mohamed-nabawy** [wnabil/ngx-export-as#16]
i think it's a matter of used font to render the characters.

**Comment by wnabil** [comment]
Support added for some file types, not all the files and used libraries supports the special/other language characters but at least the app will not crash now when exporting.
tested with: 
- PDF, PNG: chars are not connected and this issue related to html2canvas and there is a new implementation coming soon so please skip this for now until we use another library for this file types.
- CSV, MS word: Not supported at all
- txt, Excel, json, xml works fine without any issue

**Comment by wnabil** [comment]
edit: pdf and png are supported now, please use 1.2.4
