### ISSUE TITLE
Uncaught TypeError: Buffer is not a constructor

### ISSUE THREAD

**Issue by prasanna0101** [wnabil/ngx-export-as#17]
![Screenshot from 2019-05-28 17-50-21](https://user-images.githubusercontent.com/50865264/58477812-1fb94080-8172-11e9-9207-fa988f04dbc5.png)

when i add the package in imports i get this error. my Angular configurations are as follows:
Angular CLI: 7.3.9
Node: 10.15.3
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.9
@angular-devkit/core         7.3.9
@angular-devkit/schematics   7.3.9
@schematics/angular          7.3.9
@schematics/update           0.13.9
rxjs                         6.3.3
typescript                   3.2.4

**Comment by wnabil** [comment]
Hi, will check that soon 
thanks for reporting

**Comment by wnabil** [comment]
Hi, can you please check the polyfills section and try to enable them, seems your browser do not have the required polyfills just like IE.
https://github.com/wnabil/ngx-export-as#ie-users

**Comment by wnabil** [comment]
hi @prasanna0101 please confirm the issue or the fix if it works for you so i can close this issue or try to find a fix for you

**Comment by prasanna0101** [comment]
@wnabil  yes i have enabled the polyfills and added the typedarray.js also. it is not working.

**Comment by prasanna0101** [comment]
@wnabil i followed this link https://github.com/SheetJS/js-xlsx/issues/1215#issuecomment-447744879 and it is working. Thanks for your support.

**Comment by wnabil** [comment]
Great thank you for the info
