### ISSUE TITLE
pagebreak

### ISSUE THREAD

**Issue by salamkg** [wnabil/ngx-export-as#19]
can't understand how to fix page breaks. I have multiple pages of data but some pages break data so they remain separated into two parts on previous page and next page

**Comment by wnabil** [comment]
Hi, which format you are talking about ?

**Comment by salamkg** [comment]
pdf format

**Comment by wnabil** [comment]
Please check for html2pdf library options and pdfjs for custom options as well, this library doesn't have any configuration to manage it and sadly i do not know how to do it ether.
https://github.com/eKoopmans/html2pdf.js
