### ISSUE TITLE
Can't export to PDF

### ISSUE THREAD

**Issue by jevilla94** [wnabil/ngx-export-as#2]
Hello

I'm using this module to export a ngx content to pdf, but at the moment of try to export it the file isn't creating. The code is:

Module: 
import { NgModule } from '@angular/core';

import { ThemeModule } from '../../@theme/theme.module';
import { SharedModule } from '../../shared/shared.module';
import { CertificadosRoutingModule, routedComponents } from './certificados-routing.module';
import { NgxQRCodeModule } from 'ngx-qrcode2';
import { ExportAsModule } from '../../../../node_modules/ngx-export-as/lib/index';
import { PruebaQrComponent } from './prueba-qr/prueba-qr.component';

@NgModule({
  imports: [
    ThemeModule,
    SharedModule,
    CertificadosRoutingModule,
    NgxQRCodeModule,
    ExportAsModule,
  ],
  declarations: [
    ...routedComponents,
    PruebaQrComponent,
  ],
  providers: [
    SharedModule,
  ],
})
export class CertificadosModule {
}

Component: 
import { Component, OnInit } from '@angular/core';
import { ExportAsService, ExportAsConfig } from '../../../../../node_modules/ngx-export-as/lib/index';

@Component({
  selector: 'ngx-prueba-qr',
  templateUrl: './prueba-qr.component.html',
  styleUrls: ['./prueba-qr.component.scss'],
})
export class PruebaQrComponent implements OnInit {
  campusvirtual = 'https://campusvirtual.udistrital.edu.co';
  google = 'https://google.com.co';
  config: ExportAsConfig = {
    type: 'pdf',
    elementId: 'mytable',
  };

  constructor(private exportAsService: ExportAsService) { }
  exportAs(type) {
    this.config.type = type;
    this.exportAsService.save(this.config, 'file');
  }
  ngOnInit() {
  }
}

HTML:
<nb-card>
  <nb-card-header>
    <h2>QR y PDF</h2>
  </nb-card-header>
  <nb-card-body id="mytable">
    <ngx-qrcode qrc-element-type="url" [qrc-value]="campusvirtual" qrc-version="3"></ngx-qrcode>
    <ngx-qrcode qrc-element-type="url" [qrc-value]="google" qrc-version="3" qrc-errorCorrectionLevel="H"></ngx-qrcode>

    <button (click)="exportAs('pdf')">export as pdf</button>
    <button (click)="exportAs('png')">export as png</button>
  </nb-card-body>
</nb-card>

Please, I need your help

**Comment by wnabil** [comment]
Hi,
This module uses the element id as a selector for your table to export it, the options object have elementID property, please add an id to your element in the html file and use the same on the options.

**Comment by jevilla94** [comment]
I have done those modifications:
Component:
import { Component, OnInit } from '@angular/core';
import { ExportAsService, ExportAsConfig } from '../../../../../node_modules/ngx-export-as/lib/index';

@Component({
  selector: 'ngx-prueba-qr',
  templateUrl: './prueba-qr.component.html',
  styleUrls: ['./prueba-qr.component.scss'],
})
export class PruebaQrComponent implements OnInit {
  campusvirtual = 'https://campusvirtual.udistrital.edu.co';
  google = 'https://google.com.co';
  **config: ExportAsConfig = {
    type: 'pdf',
    elementId: 'myfile',
  };**

  constructor(private exportAsService: ExportAsService) { }
  exportAs(type) {
    this.config.type = type;
    this.exportAsService.save(this.config, 'file');
  }
  ngOnInit() {
  }
}

HTML:
[nb-card>
  [nb-card-header>
    [h2>QR y PDF</h2>
  [/nb-card-header>
  [nb-card-body id="myfile">
    [ngx-qrcode qrc-element-type="url" [qrc-value]="campusvirtual" qrc-version="3"></ngx-qrcode>
    [ngx-qrcode qrc-element-type="url" [qrc-value]="google" qrc-version="3" qrc-errorCorrectionLevel="H"></ngx-qrcode>

    [button (click)="exportAs('pdf')">export as pdf</button>
    [button (click)="exportAs('png')">export as png</button>
  [/nb-card-body>
[/nb-card>"

But the problem persist

**Comment by jevilla94** [comment]
In the browser console show this: 
0ms html2canvas: html2canvas $npm_package_version
Logger.js:36
1ms html2canvas: onrendered option is deprecated, html2canvas returns a Promise with the canvas as the value
Logger.js:50
1685ms html2canvas: Document cloned, using computed rendering
Logger.js:36
1686ms html2canvas: Starting node parsing
Logger.js:36
1717ms html2canvas: Added image data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJQAAACUCAYAAAB1PADUAAAEOklEQVR4nO2ZSW4kQQzE+v+fnrkm7IMgBJVLmwTqlFmhpdgX+/NPBORzugH5LhRKUBRKUBRKUBRKUBRKUBRKUBRKUBRKUBRKUBRKUBRKUBRKUBRKUBRKUGKhPp/P1md3vzTdes/tNw54bWCFUiiFemi/ccBrAyvUW0LRTAtVnd8m4O35ClWcK1Qz77
Logger.js:36
1746ms html2canvas: Added image data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJQAAACUCAYAAAB1PADUAAAEY0lEQVR4nO2Y22rkMBAF5/9/evdVeCCic6p1carAT5ZPX1QDIZ9/IiCf3Q3Iu1AoQVEoQVEoQVEoQVEoQVEoQVEoQVEoQVEoQVEoQVEoQVEoQVEoQVEoQYmF+nw+S5+0n+7z1X5v2++037cNrFAKpVAX7Xfa79sGVqiXCUWTClU9T9dL93Pafqd5pz
Logger.js:36
1759ms html2canvas: Finished parsing node tree
Logger.js:36
2190ms html2canvas: Finished loading 2 images 
Array [ img, img ]
Logger.js:36
2194ms html2canvas: Starting renderer
Logger.js:36
2197ms html2canvas: Canvas renderer initialized (973x350 at 292,-57.600006103515625) with scale 1
Logger.js:36
2267ms html2canvas: Render completed
Logger.js:36

**Comment by wnabil** [comment]
Please post here your system specs and what version of angular you are using and any related modules.
Also it will be better if you can create a repo on github

**Comment by jevilla94** [comment]
Angular CLI: 1.7.3
Node: 9.4.0
OS: linux x64
Angular: 5.1.3
Platform: ngx-admin
Repo: isn't possible for now

**Comment by jevilla94** [comment]
Repo: https://github.com/jevilla94/generador_certificados/tree/certificados

**Comment by wnabil** [comment]
Hi, i tested it, yeah actually there is an update with jspdf, its not working with html2canvas anymore.
i will update the package today or tomorrow, Thanks for reporting.

**Comment by wnabil** [comment]
As a temp solution until the jspdf update the addHTML method, i downgraded the html2canvas library, please try version 0.0.7-alfa.

**Comment by miigangls** [comment]
@wnabil How do I install version 0.0.7-alpha. in node.js?

**Comment by wnabil** [comment]
```bash npm install --save ngx-export-as@0.0.7-alpha ```

or

```bash npm install --save ngx-export-as@latest ```

https://docs.npmjs.com/cli/install

**Comment by jevilla94** [comment]
npm install --save ngx-export-as@0.0.7-alfa

**Comment by jevilla94** [comment]
Hello again

I am trying to use this library in a similar development, this has the following features:

Angular CLI: 7.3.6
Node: 10.15.3
OS: win32 x64
Angular:
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.6
@angular-devkit/core         7.3.6
@angular-devkit/schematics   7.3.6
@schematics/angular          7.3.6
@schematics/update           0.13.6
rxjs                         6.3.3
typescript                   3.2.4

And this error is presented again 
![image](https://user-images.githubusercontent.com/35529361/54873568-adf5fc80-4da6-11e9-8e0d-a2775db67ffc.png)

I'll be attentive to any help you can give me again

**Comment by wnabil** [comment]
@jevilla94 
Please check this issue.
https://github.com/MrRio/jsPDF/issues/1610
As a temp solution please install html2canvas manually until i update the package
`npm install --save html2canvas@0.5.0-beta4`
