### ISSUE TITLE
Export the record of only single page

### ISSUE THREAD

**Issue by rahulguptafullstack** [wnabil/ngx-export-as#20]
Hi,
I have multiple pages record data in table, but this library export only first page of record.
I want to export pages of data in single click.

**Comment by wnabil** [comment]
Hi
What format is this please ? 
please make sure you are using the latest version and checked the custom options for your file format used library
https://github.com/wnabil/ngx-export-as#used-libraries-useful-for-custom-format-options
https://github.com/wnabil/ngx-export-as#configuration
you can check the demo for more examples

**Comment by rahulguptafullstack** [comment]
Hi,
I have install the library yesterday as given procedure and  used the custom options  format as given

const exportAsConfig: ExportAsConfig = {
  type: 'pdf', 
  elementId: 'usersList', // id of table
  options: { // html-docx-js document options
    orientation: 'landscape',
    margins: {
      top: '20'
    }
  }
}

**Comment by wnabil** [comment]
yes the second one is the correct one but sadly the bugs for the used libraries are not managed by this project, check for html2pdf and jspdf issues and workaround please, sadly i do not know how to fix this bug

**Comment by rahulguptafullstack** [comment]
If you can fix this issue then it will be better.
