### ISSUE TITLE
Rupee symbol not showing

### ISSUE THREAD

**Issue by apbedi** [wnabil/ngx-export-as#23]
Unable to download csv file when I am using rupee symbol in my html content.  
Error showing failed to execute 'btoa' on 'window'.  The string to be encoded contains characters outside of latin1 range. Same code when I am using for xls it works for me

**Comment by wnabil** [comment]
will check this soon, please add an example table data so i can debug with it.

**Comment by wnabil** [comment]
Tested and working, please make sure you installed version `1.2.3` or above
Updated demo with example
