### ISSUE TITLE
Export to pdf blank when hiding table using css display

### ISSUE THREAD

**Issue by Hojekunle** [wnabil/ngx-export-as#26]
Hi Wnabil.
Thank you for the great work.
Export to pdf goes blank when hiding the table using css display property.

I had implemented searching, sorting and pagination on the server and noticed export displays only the data on the current page. The challenge was to display all data and not just data on the current page. Hence i thought about using a second table with all data but hiding it and export shows nothing when exporting to pdf. Kindly advice if there is a way around this.

Thanks for your help

**Comment by Hojekunle** [comment]
Hi Wnabil.
Thank you for the great work.
Export to pdf goes blank when hiding the table using css display property.

I had implemented searching, sorting and pagination on the server and noticed export displays only the data on the current page. The challenge was to display all data and not just data on the current page. Hence i thought about using a second table with all data but hiding it and export shows nothing when exporting to pdf. Kindly advice if there is a way around this.

Thanks for your help

**Comment by wnabil** [comment]
Hi,
You can check this issue i explained some details for a workaround
https://github.com/wnabil/ngx-export-as/issues/24
Please try it and tell me if that helps or not

**Comment by Hojekunle** [comment]
Hi Wnabil
Thanks for the quick feedback. Doing like you mentioned gave me the error in a below. I tried doing like b below and it only worked on the second click. Obviously the table was yet to be loaded as at when the pdf was generated.
I think the ideal scenario in my case would be to bind the table renderer to the datasource itself and not the table id so that i wouldnt need 2 tables on a page and display both at the point the user is generating report. The end user will be confused . But then this library was probably not built for that purpose. Any ideas on any library built this way?

 a. ERROR in src/app/app.component.ts(32,54): error TS2339: Property 'subscribe' does not exist on type 'void'.
 
 b. export class AppComponent {
  display: any = false;
  
  exportAs(type: SupportedExtensions, opt?: string) {
    this.display = true;
    this.config.type = type;
    if (opt) {
      this.config.options.jsPDF.orientation = opt;
    }
    this.exportAsService.save(this.config, 'myFile');

**Comment by wnabil** [comment]
` Property 'subscribe' does not exist on type 'void'.`
install the latest version first and retry please

**Comment by wnabil** [comment]
@Hojekunle please confirm so we can close the issue

**Comment by lostmagicK** [comment]
Use [hidden] property binding it is helpful

**Comment by Hojekunle** [comment]
Well Wnabil, you can close the issue. My thought about using 2 tables and hiding one for export purposes only doesnt seem a good approach. My requirement will be to bind the table to the datasource and not the table Id (so that even when the data is paginated from the server, the tool will export all data and not just data on the first page), so that i can still control pagination, sorting on the server. 
Im looking elsewhere until that is supported. Thanks again.
