### ISSUE TITLE
Unable to install it in angular 8 project.

### ISSUE THREAD

**Issue by NavneetVaid** [wnabil/ngx-export-as#29]
I am getting below error while installing it in angular 8 project:
npm ERR! code 128
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! error: waitpid for git-submodule failed: No child processes

**Comment by wnabil** [comment]
This error is not a package specific one, it can be happens for multiple reasons like internet connection or old npm version.
also it is not related to jspdf 
https://github.com/MrRio/jsPDF/issues/2537

![image](https://user-images.githubusercontent.com/23165327/61577372-c96bdc80-aae6-11e9-8343-21ecc24163c4.png)

please check this question at stackoverflow
https://stackoverflow.com/questions/47033257/error-waitpid-for-fetch-pack-failed-no-child-processes

**Comment by NavneetVaid** [comment]
This is not related to git. I am not able to install this package in Angular 8 application. I am not able to reach to the stage where i see added 75 packages.
