### ISSUE TITLE
PDF Multiple Pages

### ISSUE THREAD

**Issue by jevilla94** [wnabil/ngx-export-as#3]
Hello, one more time.
First, thank you for to solve before problem.
Now the problem is to generate multiple pages; that is associated whit other issue that you search a solution (canvas height). I have received the code of the html2canvas library and it's possible change the height if you modify this line: 
module.exports = function(ownerDocument, containerDocument, width, height, options, x ,y) {
    var documentElement = cloneNode(ownerDocument.documentElement, options.javascriptEnabled);
    var container = containerDocument.createElement("iframe");

    container.className = "html2canvas-container";
    container.style.visibility = "hidden";
    container.style.position = "fixed";
    container.style.left = "-10000px";
    container.style.top = "0px";
    container.style.border = "0";
    container.width = width;
    **container.height = "1500px";**//before height;
    container.scrolling = "no"; // ios won't scroll without it
    containerDocument.body.appendChild(container); 

I don't know if exist one way to solve it whit your module. I would appreciate any help

Also changing the size of the sheet without affecting the library code

**Comment by wnabil** [comment]
Hi, sadly i have exams this week and i will back to work after about 10
days, if you want you can make a pull request and i will merge it or edit
some of it.

you can build the project by running npm run build.

**Comment by endouAxel** [comment]
I am using ng export as  library can we have multiple pages instead of single page
