### ISSUE TITLE
No Data When Use PDF , PNG

### ISSUE THREAD

**Issue by mosmohamed** [wnabil/ngx-export-as#30]
Al Salam Alaykom ,

thanks for this great package but i have issue when export as pdf or png no data shown
but it's work good when export as excel any hint ??

Angular (7)

**Comment by wnabil** [comment]
وعليكم السلام ورحمة الله وبركاته
I think you are exporting a hidden element? if so please make it visible first or it doesn't work.

**Comment by mosmohamed** [comment]
no i didn't hava any hidden element 
i have table with 10 row and this is result when export 

![image](https://user-images.githubusercontent.com/36249181/62000950-d1c6a780-b0e4-11e9-95bd-cf53b42fc737.png)

**Comment by wnabil** [comment]
Which version you are using ? can you please upgrade to latest and try.

**Comment by wnabil** [comment]
@mosmohamed Please any updates on this ?

**Comment by rubaawata** [comment]
Hello:
I have same issue, text and table when export to pdf or png table not shown in result.
and  i use latest version
Thanks..

**Comment by mosmohamed** [comment]
> @mosmohamed Please any updates on this ?

unfortunately I don't have a time to debug it so i go to server side rendering

**Comment by wnabil** [comment]
@rubaawata 
can you please include your system details and used tools version like angular cli/version?

**Comment by rubaawata** [comment]
sorry for late reply.
[package.txt](https://github.com/wnabil/ngx-export-as/files/3538540/package.txt)
thanks

**Comment by wnabil** [comment]
please reopen if the issue still exists in the latest version, i tested it and had no issues
