### ISSUE TITLE
Cannot run the demo

### ISSUE THREAD

**Issue by AlaaHamoudah** [wnabil/ngx-export-as#31]
I am trying to run the demo but I am facing this problem on `ng serve` step

```ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/array' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/date' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/function' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/map' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/math' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/number' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/object' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/parse-float' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/parse-int' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/reflect' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/regexp' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/set' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/string' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/symbol' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/weak-map' in '/Users/alaahamoudah/Documents/git/ngx-export-as/src'
```

I tired it in angular 7 and 8 and the same problem occur.

**Comment by wnabil** [comment]
Hi,

The error is not something related to the package, this error is a mismatch for the core-js version in your project or maybe because you are using an old angular cli.

https://stackoverflow.com/questions/54505024/getting-error-in-src-polyfills-ts-while-running-ng-build-prod

https://stackoverflow.com/questions/55308769/module-not-found-error-cant-resolve-core-js-es6

**Comment by AlaaHamoudah** [comment]
Oh yeah I fix the error and run the demo, amazing work thank you, quick question, does it support utf-8 ?? and can I print something with a different style than the browser?
<img width="348" alt="Screen Shot 2019-08-27 at 2 38 26 PM" src="https://user-images.githubusercontent.com/1776802/63768276-7997e680-c8d8-11e9-985d-c45d72e9b8b0.png">

**Comment by wnabil** [comment]
yes it supports the utf-8 but make sure you are using the latest version of the package.
for custom styles it is depends on the type of your exported file. for example : for png and pdf there is 2 ways to set a custom styles, you can set the styles in the html directly and your exported file will have the same styles. The second way is to add the styles in the custom options if the used library supports them. check the section in read me for the used libraries references and how to use the custom options
https://github.com/wnabil/ngx-export-as#used-libraries-useful-for-custom-format-options

https://github.com/wnabil/ngx-export-as#configuration

**Comment by timothyr** [comment]
Hi, I built this project locally and ran into the same issue as above. I bumped core-js version from 2.5.7 -> 3.6.5 and it built without errors. Consider updating the core-js version in packages.json.
```
    "core-js": "^3.6.5",
```

**Comment by JaniceBPC** [comment]
It is "core-js": "^3.6.5" and it still does not work
ran npm update
same error:
  ERROR in ./src/polyfills.ts
  Module not found: Error: Can't resolve 'core-js/es6/reflect'

**Comment by wnabil** [comment]
this issue is fixed in the latest release you do not have to downgrade your core-js version anymore
use the latest version and delete node_modules then do npm i
