### ISSUE TITLE
No options for removing the column formatting!!

### ISSUE THREAD

**Issue by MnemosyneMei** [wnabil/ngx-export-as#32]
This is no options or parameter for me to pass in for avoid auto format the data from each columns. For example, the string 0001234, it will become 1234 in excel and +621212, will become 621212 in excel. I wish there is some options to avoid the data lost.

**Comment by wnabil** [comment]
its mentioned here that there is an option for this
https://github.com/SheetJS/sheetjs/issues/748
`raw: true`
please reopen if it doesn't help
