### ISSUE TITLE
Strict mode code may not include a with statement

### ISSUE THREAD

**Issue by jwhijazi** [wnabil/ngx-export-as#36]
I used the module before with Angular 7 and it worked as expected.
Today I tried to use it with Angular 8 project and the whole project returned an error:

"Strict mode code may not include a with statement"
Can you solve this problem for us please.

**Comment by wnabil** [comment]
This issue already stated here
https://github.com/wnabil/ngx-export-as/issues/21
we still do not work on this yet and as mentioned any PR to replace htmldocx lib is welcome
