### ISSUE TITLE
Unable to build through npm

### ISSUE THREAD

**Issue by limthengwai** [wnabil/ngx-export-as#37]
I tried to install this package through npm but it failed. Please let me know any of you faced the same problem or any fixes. 

/*ERROR START HERE*/
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
npm ERR!
npm ERR! undefined
npm ERR! exited with error code: 128
/*ERROR END HERE*/

**Comment by wnabil** [comment]
what command you are using for install ? make sure to use the same command from readme file

**Comment by limthengwai** [comment]
> what command you are using for install ? make sure to use the same command from readme file

yes, I used the same command in the readme file.

command used: 
npm install --save ngx-export-as

**Comment by wnabil** [comment]
Can you try installing any other package !? if it works then try to upgrade your npm 
if not then seems your ISP blocks the npm from downloading the packages
![image](https://user-images.githubusercontent.com/23165327/66748800-5fb26300-ee88-11e9-9ab1-de065a5ff285.png)
