### ISSUE TITLE
html2pdf not defined with ssr builds

### ISSUE THREAD

**Issue by sherry9872** [wnabil/ngx-export-as#39]
Hi,
I am getting the below error with production build

ReferenceError: html2pdf is not defined
    at Object.eval (webpack:///./node_modules/jspdf/dist/jspdf.min.js?:207:16291)

![image](https://user-images.githubusercontent.com/20853309/67145593-510ce700-f2a0-11e9-98e1-96880211bc73.png)

**Comment by wnabil** [comment]
Can u please add the steps you used to build the project so i can fix this for you ?
did not work with SSR since angular 4 is out

**Comment by wnabil** [comment]
@sherry9872 any news ?

**Comment by wnabil** [comment]
i found a fix here
please check it
https://github.com/MrRio/jsPDF/issues/2226
