### ISSUE TITLE
Failed to run ngx-export-as repo

### ISSUE THREAD

**Issue by donacoba090909** [wnabil/ngx-export-as#4]
Hi mate,
 I'll find your tool interesting that I need this in my project but I tried to run the sample but it gives me the error.
npm install
ng build 
ng serve

![image](https://user-images.githubusercontent.com/20560079/38291922-1da63150-3825-11e8-9cc5-92300c286e41.png)

**Comment by wnabil** [comment]
Hi, yes there is a changes with the new angular cli that breaks with my project config, i will try to fix it in the next few days, Thanks for reporting that.
