### ISSUE TITLE
Date column subtracts 1 hour from the list. Excel download

### ISSUE THREAD

**Issue by jayendranshan** [wnabil/ngx-export-as#41]
Hi,
I have a excel download where i am exporting a list and one of the columns is date. For some reason all the month except current month date is showing 1 day minus. When i check the time it shows 11.00 PM previous day instead of current date 12.00 AM. 
In the below example, the date shows as "07/09/2019 11:00:00PM" and it should show as  "07/10/2019 12:00:00PM" . I even converted this string but the issue still remain same.
Has any one faced this issue before?
![image](https://user-images.githubusercontent.com/8661873/68916598-b2579700-0734-11ea-87d3-079b20680fdb.png)

**Comment by wnabil** [comment]
Yes seems https://github.com/SheetJS/sheetjs have some special styles for the data types i ran into a similar problem before.
please see the issues there as this is not something related to our package.
