### ISSUE TITLE
not getting table borders while exporting as doc 

### ISSUE THREAD

**Issue by pchoure** [wnabil/ngx-export-as#42]
i am exporting the data by its element id in "doc" format .
My data has multiple tables, so after exporting the data seems fine .

But facing some css issues,for example- table borders are not visible in doc file .

I am using angular 6.

**Comment by wnabil** [comment]
try exporting the container of the table instead of the table itself, doc format doesn't require the element to be a table.

**Comment by pchoure** [comment]
I have given an id to the body tag of the HTML  which contains multiple tables and header tags.
And i am exporting it by using that  body tag id itself.
All the css are already included in its .css file.

**Comment by wnabil** [comment]
can you please upload a sample project with the issue so i can debug it for you, i checked html-docx-js and it seems there is no issues with the borders
