### ISSUE TITLE
How to export PDF with custom css and (foreign) images

### ISSUE THREAD

**Issue by nirav5884** [wnabil/ngx-export-as#43]
I have html tags with custom css, multiple images (src URLs) and videos inside my DIV.
I want to export all in single PDF (with multiple pages).
What all things possible here and how to do?
I am trying to export large div but it doesn't export the complete and only exports what is displaying on screen.
And all my images are missing from exported PDF.

**Comment by wnabil** [comment]
This library doesn't support the advanced methods by default.
You might find a way to manage this using the pdf options from https://github.com/eKoopmans/html2pdf.js and if you were not able to do so then i suggest you to remove this package and use the pure html2pdf or pdf js library as it will be more flexible in customizing single format.
