### ISSUE TITLE
anyway that I can change height or width of col in excel. 

### ISSUE THREAD

**Issue by kotran88** [wnabil/ngx-export-as#44]
Hello 
It' really nice and easy to use it on ionic

1. wonder if there's a way that I can change width , height of col and row....?
2. I just implemented it on my ionic 3 project and it works very well. on web(run by ionic serve and once I click export as Ms-Excel. then xls. file is doneloaded )

but not on real mobile device. 
is there a way that I can export and download to my real device on ionic project? 

Thank you

**Comment by wnabil** [comment]
1- Check the custom options for xls library
2- You have to use the .get method then use a cordova file plugin to save the content to the device.
