### ISSUE TITLE
doc/docx formats not working. ERROR: Export type is not supported

### ISSUE THREAD

**Issue by skopekreep** [wnabil/ngx-export-as#46]
Great package, thank you.

I noticed that in my own app, as well as the current demo, the doc/docx formats produce the error listed above.  The other export types seem to be working properly (at least in that they produce a download).

**Comment by wnabil** [comment]
use version 1.3.1

**Comment by shitallakhe** [comment]
i use this version but i face another issue like Uncaught SyntaxError: Strict mode code may not include a with statement

**Comment by wnabil** [comment]
@shitallakhe https://github.com/wnabil/ngx-export-as#change-logs

**Comment by Sowmya-Sukhanand** [comment]
I use version 1.4.2....i've 
![image](https://user-images.githubusercontent.com/55222218/87931290-2a861180-caa7-11ea-9f2a-aa6317c9c73c.png)
