### ISSUE TITLE
run on ionic4 get error

### ISSUE THREAD

**Issue by zhujin001032** [wnabil/ngx-export-as#50]
![image](https://user-images.githubusercontent.com/7955640/72244765-ee6e8180-3629-11ea-84e5-4d9754b8febf.png)

**Comment by wnabil** [comment]
Thanks for reporting, please post here all package.json file content

**Comment by zhujin001032** [comment]
{
  "name": "newMetaDataApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.15",
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/app-version": "^5.13.0",
    "@ionic-native/background-mode": "^5.3.0",
    "@ionic-native/base64-to-gallery": "^5.19.0",
    "@ionic-native/camera": "^5.5.1",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/file": "^5.5.1",
    "@ionic-native/file-opener": "^5.13.0",
    "@ionic-native/file-path": "^5.5.1",
    "@ionic-native/file-transfer": "^5.13.0",
    "@ionic-native/geolocation": "^5.5.1",
    "@ionic-native/image-picker": "^5.5.1",
    "@ionic-native/in-app-browser": "^5.17.1",
    "@ionic-native/ionic-webview": "^5.12.0",
    "@ionic-native/keyboard": "^5.17.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.11.3",
    "@ionic/storage": "^2.2.0",
    "@jiguang-ionic/jpush": "^2.0.0",
    "chart.js": "^2.8.0",
    "com.jasonhe.cordova.screenshot": "^1.0.6",
    "cordova-android": "7.1.4",
    "cordova-android-support-gradle-release": "^3.0.1",
    "cordova-base64-to-gallery": "^4.1.3",
    "cordova-ios": "5.1.1",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-adam-wechat": "^3.0.6",
    "cordova-plugin-alipay-v2": "git+https://github.com/hhjjj1010/cordova-plugin-alipay-v2.git",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-baidumaplocation": "git+https://github.com/AndrewWen099/ionic-plugin-baidumaplocation.git",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^2.2.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-filepath": "^1.5.6",
    "cordova-plugin-inappbrowser": "^3.1.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.2",
    "cordova-plugin-jcore": "^1.3.1",
    "cordova-plugin-splashscreen": "git+https://github.com/zhujin001032/cordova-plugin-splashscreen.git",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-telerik-imagepicker": "^2.3.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "dom-to-image": "^2.6.0",
    "dom-to-picture": "^0.1.2",
    "echarts": "^4.2.1",
    "html-element-to-image": "^2.1.0",
    "ionic-cache": "^4.0.1",
    "jpush-phonegap-plugin": "^3.7.3",
    "ng-socket-io": "^0.2.4",
    "ng-zorro-antd-mobile": "^0.12.5",
    "ng2-charts": "^2.3.0",
    "ngx-echarts": "^4.2.1",
    "ngx-export-as": "^1.4.0",
    "node": "^11.4.0",
    "qrcode": "^1.4.4",
    "rxjs": "~6.5.1",
    "rxjs-compat": "^6.5.2",
    "strophe.js": "^1.3.4",
    "tslib": "^1.9.0",
    "vconsole": "^3.3.4",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.13.8",
    "@angular-devkit/build-angular": "~0.13.8",
    "@angular-devkit/core": "~7.3.8",
    "@angular-devkit/schematics": "~7.3.8",
    "@angular/cli": "~7.3.8",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "~1.5.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.0.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.1.0",
    "tslint": "~5.16.0",
    "typescript": "^3.2.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-file": {},
      "cordova-plugin-actionsheet": {},
      "cordova-plugin-telerik-imagepicker": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "上传图片需要访问您的相册"
      },
      "cordova-plugin-filepath": {},
      "cordova-android-support-gradle-release": {
        "ANDROID_SUPPORT_VERSION": "27.+"
      },
      "com.jasonhe.cordova.screenshot": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": " ",
        "PHOTO_LIBRARY_ADDITIONS_USAGE_DESCRIPTION": " "
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-adam-wechat": {
        "WECHATAPPID": "wx598456e65e41****"
      },
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-baidumaplocation": {
        "ANDROID_KEY": "xyAzSFz25ikzo2GDyX3ZMNysU1HG04Re",
        "IOS_KEY": "HezdKbIcIDzu64uAQHHeVB2sC2h5****",
        "IOS_LOCATION_DESC": "请点击'好'以允许访问。"
      },
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-file-opener2": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-alipay-v2": {
        "APP_ID": "2017081508209526"
      },
      "cordova-plugin-device": {},
      "jpush-phonegap-plugin": {
        "APP_KEY": "1b6248dd26f17cfa4782****",
        "CHANNEL": "developer-default"
      },
      "cordova-plugin-inappbrowser": {},
      "cordova-base64-to-gallery": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}

**Comment by zhujin001032** [comment]
![WX20200115-144500](https://user-images.githubusercontent.com/7955640/72411359-a70d0000-37a5-11ea-9b05-b4ba69ad411a.png)

All ionic4 elements has the "#show-root"

**Comment by wnabil** [comment]
so you got the error during the plugin install or on app start or when trying to export ?

**Comment by zhujin001032** [comment]
got the error when trying to export ；And the export png lost all img.
![32D7BCA9-A80A-4318-8E2E-EEEDC7A86BD9](https://user-images.githubusercontent.com/7955640/75640719-f71a2600-5c70-11ea-8ef5-133cebc661f4.png)

**Comment by elamoraz** [comment]
I'm experiencing the same error. Is a problem with web components and html2canvas

**Comment by wnabil** [comment]
@elamoraz 
@zhujin001032 
use useCORS: true in the options its html2canvas issue
