### ISSUE TITLE
Export is corrupted

### ISSUE THREAD

**Issue by lustuyck** [wnabil/ngx-export-as#51]
I'm trying to export a div that contains labels and some ngx-charts, but the resulting pdf or png is corrupted. It doesn't scale the image and therefore half of it (both width and height) is missing in the resulting pdf or png (see attachment). 
[My File Name (2).pdf](https://github.com/wnabil/ngx-export-as/files/4070353/My.File.Name.2.pdf)

**Comment by wnabil** [comment]
I think its a css issue, try setting the containers max width to 100%
