### ISSUE TITLE
Error when i trying to run demo

### ISSUE THREAD

**Issue by wHerex** [wnabil/ngx-export-as#54]
When i trying to run demo after command ng serve i can see this errors , server start anyway but browser display only "Cannot GET /"

ERROR in ./src/polyfills.ts 
Module not found: Error: Can't resolve 'core-js/es/array' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/date' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/function' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/map' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/math' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/number' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/object' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/parse-float' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/parse-int' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/reflect' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/regexp' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/set' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/string' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/symbol' in '/home/marcin/IdeaProjects/ngx-export-as/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es/weak-map' in '/home/marcin/IdeaProjects/ngx-export-as/src'

**Comment by wnabil** [comment]
https://github.com/wnabil/ngx-export-as/issues/31
