### ISSUE TITLE
Does not work with Angular Universal

### ISSUE THREAD

**Issue by lkurylo** [wnabil/ngx-export-as#56]
I have used this library for export to png files.
Unfortunatelly during setup an Angular Universal, this doesn't work.
I got

```
node .\dist\server.js
D:\repo\Budget\SRC\Trunk\Budget.Api\UI\dist\server.js:318902
CacheStorage.setContext(window);
                        ^

ReferenceError: window is not defined
```

This CacheStorage is used I think in the html2canvas package. 

I tired to use domino and MockBrowser but with no result.

**Comment by wnabil** [comment]
@lkurylo please test the latest version and reopen in case if its still desn't work
