### ISSUE TITLE
production build size gets increased

### ISSUE THREAD

**Issue by farhatzaman726** [wnabil/ngx-export-as#57]
i am not sure why, but after installing and importing ngx-export-as in main module. my production build size increased from 1.3 to 1.5 mb. which is causing issues in initial loading of my app.
i think loading of xlsx.js and other imports which you are you are using in this library causing for bundle size increase.

**Comment by wnabil** [comment]
If you want a minimal use of this feature then do not use the library as it does import 3 packages to manage multiple file types, instead do the implementation manually for the specific type you want.
Check the implementation here if you needed any help
