### ISSUE TITLE
Delete a row or a column and then export to Excel

### ISSUE THREAD

**Issue by shubham708** [wnabil/ngx-export-as#58]
I built the demo example. Works perfect. 

**Given REMARKS column is visible in the HTML page, how to export all columns except _REMARKS_?**

Same question for the row. I want to export all rows except _INDONESIA_ row given it is visible in the page. How to do it?

**Comment by wnabil** [comment]
remove it from the ui before rendering then put it back, something like
`
this.exporting = true;
    this.exportAsService.save(this.exportAsConfig, 'My File Name').subscribe(() => {

     this.exporting = false;
    });
`

in the html *ngIf='!exporting'
