### ISSUE TITLE
Date is changed to ######## after file export as excel

### ISSUE THREAD

**Issue by shubham708** [wnabil/ngx-export-as#60]
![image](https://user-images.githubusercontent.com/60775064/75509046-309e2780-5a0c-11ea-827d-ed2a2c635300.png)

But as soon as the column is expanded, the date is visible again.

![image](https://user-images.githubusercontent.com/60775064/75509131-7b1fa400-5a0c-11ea-9037-d641669ea68c.png)

**How to specify the column width before export?**

Why is it not happening to other string columns?

**Comment by wnabil** [comment]
its because of the col width, check the available options in https://github.com/SheetJS/sheetjs#worksheet-object
