### ISSUE TITLE
PDFs: Support string input in addition to element ID input

### ISSUE THREAD

**Issue by zorent-zebra** [wnabil/ngx-export-as#61]
If you want to create a PDF today, you supply an elementId in the config and the code makes a PDF from the HTML in that element. We have HTML elements where we want a special PDF-view for certain elements which we don't want to appear on the page. We were wondering whether ngx-export-as could accept string content in the HTML.

It looks like html2pdf supports getting content from a string
https://github.com/eKoopmans/html2pdf.js#workflow

Could adding this feature to accept a string source element via config be possible?
https://github.com/wnabil/ngx-export-as/blob/master/projects/ngx-export-as/src/lib/export-as.service.ts#L135

This would truly help us build what we need.

Thanks!

**Comment by wnabil** [comment]
Thanks for the note, I released a new version 1.4.2 which includes support for all the available types "pdf only" now, please upgrade

**Comment by DomEscobar** [comment]
If I run ng build now, i get the error -> Argument of type '{ type: string; elementIdOrContent: string; }' is not assignable to parameter of type 'ExportAsConfig'.

**Comment by wnabil** [comment]
@DomEscobar import the interface and use it
