### ISSUE TITLE
Support Angular 9

### ISSUE THREAD

**Issue by nikoxgon** [wnabil/ngx-export-as#63]
Is there an opportunity to support **Angular 9**?

**Comment by wnabil** [comment]
currently i am very busy to update this, any PR is welcome or kindly wait until i have enough time for this

**Comment by Sreekanth2108** [comment]
Pull request for Angular V9 - https://github.com/wnabil/ngx-export-as/pull/64

**Comment by wnabil** [comment]
Thanks @Sreekanth2108
