### ISSUE TITLE
Unable to export Photo column into excel

### ISSUE THREAD

**Issue by myounism** [wnabil/ngx-export-as#65]
Hi there,
Please help me out, is there any way to export image columns as well. 
Suppose, i have 3 fields in html table, i.e; sno, name, photo.

When i export to excel,  sno, and name columns gets exported as they are simple text columns, but the photo columns remain blank in generated excel. 
Please help how to achieve it. 

Thanks & Regards 
Younis

**Comment by wnabil** [comment]
as explained in sheetjs its not supported in the free version of the library, please check here and buy the pro version if interested in the feature
if that solution is not possible for you then try exporting the url of the image from the server
https://github.com/SheetJS/sheetjs/issues/642#issuecomment-390502183
