### ISSUE TITLE
pdf export not working correctly when using underline

### ISSUE THREAD

**Issue by nrk6208** [wnabil/ngx-export-as#66]
i have a html content, under paragraph inside a span with inline style of font-weight:700(for bold) and text-decoration(for underline).
after exporting content not rendering correctly
![Screenshot_1](https://user-images.githubusercontent.com/27271479/80971022-c5bd0280-8e39-11ea-99e1-03f5f37cf8ed.png)

**Comment by wnabil** [comment]
Please report it in html to pdf library and once fixed we can update the dependencies in my package
https://github.com/eKoopmans/html2pdf.js
