### ISSUE TITLE
html2canvas rc-5

### ISSUE THREAD

**Issue by clintcfavor** [wnabil/ngx-export-as#69]
Hi! I can't seem to export my html using html2canvas version rc-5 but I am able to export it using rc-1 as of the moment. I'm trying to use rc-5 because it may have fixes cause my canvas is being clipped. Attached is one of the slide being clipped (all slides are being clipped and not following the css styles. I presume because of flex, but documentation says it supports flex)
![image](https://user-images.githubusercontent.com/19337016/82409350-1b331980-9aa0-11ea-8096-6730ca3c52d0.png)

**Comment by wnabil** [comment]
Hi, i will look into this soon thanks for reporting

**Comment by clintcfavor** [comment]
Hi @wnabil, fixed the issue on the clipping. The problem was on the html2canvas container's width is larger than the export container. I can't seem to get the rc-5 working though. :/

**Comment by clintcfavor** [comment]
And also, any idea why my css styles aren't being applied? The 'Areas of Exellence' and 'Areas of Interest' are supposed to be below the two circles. Btw, they are using flex-box. Supposed to be looking like the attached image below:
![image](https://user-images.githubusercontent.com/19337016/82551879-a2ad8500-9b93-11ea-9f7d-bd3d0e6c582b.png)

**Comment by wnabil** [comment]
I am not sure if html2canvas supports the flex layout or not, a sample code of your structure will be helpful so i can debug it for you

**Comment by clintcfavor** [comment]
Hi @wnabil, sorry for late reply, I've managed to find the problem. html2canvas somehow didn't read my sass styles, so I've created a separate .css style for the slides.

**Comment by wnabil** [comment]
perfect, closing this as its not related to the package

**Comment by clintcfavor** [comment]
Hi, @wnabil. Would just like to ask add up on the html2canvas rc-5 issue. I've tried updating it again to the latest version rc-1 -> rc-5 but still to no avail. Attaching my config file here, maybe I missed something...
![image](https://user-images.githubusercontent.com/19337016/83589946-53018d00-a587-11ea-957d-a8f2a5e4af9f.png)
![image](https://user-images.githubusercontent.com/19337016/83589957-58f76e00-a587-11ea-83d4-b28a40a4c2a1.png)

It just creates the html2pdf overlay, and then doesn't continue.
![image](https://user-images.githubusercontent.com/19337016/83590015-6dd40180-a587-11ea-9c1a-512f552b785a.png)

**Comment by wnabil** [comment]
Maybe html2canvas doesn't see the component styles, try adding them in the main theme styles
