### ISSUE TITLE
table font size style not applying

### ISSUE THREAD

**Issue by clintcfavor** [wnabil/ngx-export-as#72]
Hi, there seems to be a problem on tables. I've been trying to fix a problem on a table where it doesn't set the correct font size. I have it set on my css file to 12px but after exporting, it didn't follow the desired font size :/

I've attached screenshots for reference:
CSS File:
![image](https://user-images.githubusercontent.com/19337016/83098186-7be3d700-a0dc-11ea-88a4-11798c8a1f86.png)

Table before export:
![image](https://user-images.githubusercontent.com/19337016/83098196-843c1200-a0dc-11ea-9aa9-04d2719633b5.png)

Table after being exported to PDF
![image](https://user-images.githubusercontent.com/19337016/83098208-8aca8980-a0dc-11ea-9cb8-5733c11855d5.png)

It's also like being clumped into a small width rather than taking 100% of the column width.

**Comment by clintcfavor** [comment]
Hi, found a workaround on the font issue. I've used the font property for this instead of using the shorthand font properties. Closing this issue

**Comment by wnabil** [comment]
Put your styles in theme.scss and it should work as the component styles are not visible to html2canvas
