### ISSUE TITLE
doc/docx and xls/xlsx formats not working. ERROR: Export type is not supported 

### ISSUE THREAD

**Issue by shitallakhe** [wnabil/ngx-export-as#74]
Great Module, thank you.

I noticed that in my own app,the doc/docx and xls/xlsx formats produce the error listed above. The other export types seem to be working properly (at least in that they produce a download).
please help me for this issue

thank you

**Comment by wnabil** [comment]
getXLS and getXLSX works for me in the demo i can't reproduce the issue, for Docx yes its disabled for now because there is an issue with the SSR,I will try to publish a new version to support it back soon.

**Comment by shitallakhe** [comment]
Which version supported for generating in xls ans xlsx,I am using latest version.

**Comment by Sowmya-Sukhanand** [comment]
when can the docx be enabled so that the ionic users can get its advantage as well!!!
