### ISSUE TITLE
the doc format not working. ERROR: Export type is not supported

### ISSUE THREAD

**Issue by Sowmya-Sukhanand** [wnabil/ngx-export-as#76]
I use version 1.4.2...with the file download as pdf,png..the library works like a charm.But it is not supporting the doc even though the library's supported extension has doc format.
If i use version 1.3.1...it gives me strict code error
what might b the issue

**Comment by wnabil** [comment]
yes its disabled for now until we find a fix for the SSR
check version 1.3.1 it should be still working fine
https://github.com/wnabil/ngx-export-as#change-logs

**Comment by haseel2004** [comment]
The version 1.3.1 doesn't work with latest angular version.
Can you suggest how to make it compatible?

**Comment by wnabil** [comment]
@haseel2004 A pull request with the fix is more than welcome as i am very busy currently and cant do the upgrading part alone

**Comment by wnabil** [comment]
this is coming to be supported again, once this PR merged https://github.com/privateOmega/html-to-docx/pull/68#issuecomment-851080861

**Comment by wnabil** [comment]
Added in 1.12.1, please note that your project have to target  es2015 in tsconfig.json file or it will throw error `Cannot call a class as a function`
