### ISSUE TITLE
Export to xlsx converts string to Date

### ISSUE THREAD

**Issue by mkaa** [wnabil/ngx-export-as#8]
my table column has value  **Remarks 1**.

when I view my exported data in excel it shows **1/1/2001**

<img width="868" alt="ddd" src="https://user-images.githubusercontent.com/23371139/50759658-8eb7fa80-12a0-11e9-8a04-b639738ef27f.png">

**Comment by wnabil** [comment]
Hi, can you please check the string format for any special characters
also please make a repo and upload a code to reproduce this issue, i have tested it with the demo and could not reproduce the issue.

**Comment by mkaa** [comment]
i tried this

<img width="204" alt="tb" src="https://user-images.githubusercontent.com/23371139/50803656-8fdf3b00-1325-11e9-954f-b7ddb62a08cd.png">

<img width="320" alt="ex" src="https://user-images.githubusercontent.com/23371139/50803661-94a3ef00-1325-11e9-9192-16b18dd939ce.png">

Remarks 1 & 2 still converted to date when exported in excel.

i'll try to make a repo.

**Comment by wnabil** [comment]
Hi, after debugging this issue i can confirm that its related to [js-xlsx](https://github.com/SheetJS/js-xlsx)
![image](https://user-images.githubusercontent.com/23165327/51308673-51473000-1a4b-11e9-9943-05f7b1480b0f.png)
and this happened exactly at method called `table_to_sheet`
Please open an issue on that repo and reference this one so i can track the progress.
