### ISSUE TITLE
Support Angular 10

### ISSUE THREAD

**Issue by geno-github** [wnabil/ngx-export-as#84]
Currently, the Angular upgrade process will fail with this message when using the latest version of your package:

`Package "ngx-export-as" has an incompatible peer dependency to "@angular/common" (requires "^8.1.1" (extended), would install "10.1.2").
Package "ngx-export-as" has an incompatible peer dependency to "@angular/core" (requires "^8.1.1" (extended), would install "10.1.2").`

My request is to update the package so upgrades go more smoothly.  Thank you for your work, this is a very useful tool.

**Comment by wnabil** [comment]
Thanks for the info, will try to work on this in the next week, any PR is welcome

**Comment by kgish** [comment]
+1

**Comment by kgish** [comment]
This is an urgent requirement for an important update I am doing. When do you expect to have this ready? Thanks alot in advance!

**Comment by kgish** [comment]
https://github.com/wnabil/ngx-export-as/pull/85

**Comment by wnabil** [comment]
Thanks for the help again, upgrade using `npm i --save ngx-export-as@latest`
