### ISSUE TITLE
Issue when building with Docker

### ISSUE THREAD

**Issue by syfqpipe** [wnabil/ngx-export-as#86]
Hi. I've installed this package and everything run smoothly in my local serve.
Unfortunately, when I build with Docker, I got

<img width="870" alt="Screenshot 2020-10-15 at 5 27 46 PM" src="https://user-images.githubusercontent.com/64249939/96206159-e5388980-0f9a-11eb-952f-06890464fa35.png">

Below is my Dockerfile
`FROM node:lts-alpine as build-stage`
`WORKDIR /app`
`COPY package*.json ./`
`RUN npm install`
`COPY . .`
`RUN npm run build --prod`
`FROM nginx:stable-alpine as production-stage`
`COPY --from=build-stage /app/dist /usr/share/nginx/html`
`EXPOSE 80`
`CMD ["nginx", "-g", "daemon off;"]`

But after I uninstall this package, I was able to build with Docker again with no problem.

Thanks in advance!

**Comment by wnabil** [comment]
please try 1.12.1 and reopen if the issue not fixed
