### ISSUE TITLE
Quality image result

### ISSUE THREAD

**Issue by andresfocus** [wnabil/ngx-export-as#87]
the quality of the generated image is very poor

original page:

![image](https://user-images.githubusercontent.com/70960953/98158020-0d8c1780-1eb9-11eb-9af8-7bae6ee1ad25.png)

generated image:

![image](https://user-images.githubusercontent.com/70960953/98158060-1d0b6080-1eb9-11eb-9bc1-8545f468dbf2.png)

Any recommendation?

Thanks!

**Comment by wnabil** [comment]
Hi
This doesn't looks like a quality issue its more like coloring/css issue
maybe there is an animation played when doing the export and the image captured during the animation
check the demo folder for more info and html2canvas issues/options in case if that will help
https://github.com/niklasvh/html2canvas
