### ISSUE TITLE
While exporting data in JSON getting Issue

### ISSUE THREAD

**Issue by nikhilmehta7031** [wnabil/ngx-export-as#88]
Hey there,

I have built an app in angular 9 and I am using ngx-export-as version 1.4.2.
I tried to export my table data in JSON format and in response, I am getting data like below.

[{"sample":"test1213","key":"3123"}]

Also, I am getting -> ERROR Export type is not supported while exporting in doc.

In other formats like CSV, Text data export works perfectly. But this gives the issue. Please let me know if anyone has a solution for this. 

Thanks in advance.

**Comment by wnabil** [comment]
https://github.com/wnabil/ngx-export-as#important-notes

https://github.com/wnabil/ngx-export-as/issues/76
