### ISSUE TITLE
[Question] line break issue in textArea

### ISSUE THREAD

**Issue by mohammadaaqib** [wnabil/ngx-export-as#90]
line is not break in text-area, there are multiple lines in this text area but while generating pdf ,All lines are trim and text is generating in one line (kindly see image attached below)
original text-area
![neeeew](https://user-images.githubusercontent.com/14867369/111333507-9485a380-8694-11eb-91b1-39a126df4740.PNG)
after pdf generate 
![textArea](https://user-images.githubusercontent.com/14867369/111332927-04dff500-8694-11eb-86e5-76472138dfba.PNG)

**Comment by manuradisys** [comment]
Hi Team,

Anyone looking at this issue which is reported based on the line break issue

**Comment by wnabil** [comment]
its not possible with this library as explained here
https://github.com/MrRio/jsPDF/issues/758
print your textarea value in a div and it should work
