### ISSUE TITLE
Could not resolve dependency: peer @angular/common@"^10.1.3" from ngx-export-as@1.5.0 node_modules/ngx-export-as ngx-export-as@"*" from the root project

### ISSUE THREAD

**Issue by fromage9747** [wnabil/ngx-export-as#91]
Cannot install ngx-export-as.  I receive the following error:

![image](https://user-images.githubusercontent.com/23147783/114297887-6f425480-9add-11eb-975b-ed3f6cf042ab.png)

Angular CLI: 11.2.6
Node: 15.12.0
OS: darwin x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1102.6
@angular-devkit/build-angular     0.1002.0
@angular-devkit/build-optimizer   0.1100.2
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      11.2.6
@schematics/angular               10.0.8
@schematics/update                0.1102.6
rxjs                              6.5.5
typescript                        4.1.5

**Comment by rafaelblink** [comment]
If you pass the `--force` will install, just installed here and it's working perfectly, with some warns on installation but working fine.

**Comment by wnabil** [comment]
updated
used 1.12.0+
