### ISSUE TITLE
Support Angular 11

### ISSUE THREAD

**Issue by rcarreo** [wnabil/ngx-export-as#93]
Currently, the Angular 11 shows following message when I try to install your package:

npm ERR! Found: @angular/common@11.2.14
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~11.2.13" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.1.3" from ngx-export-as@1.5.0
npm ERR! node_modules/ngx-export-as
npm ERR!   ngx-export-as@"*" from the root project

My request is to update the package to be ready for support Angular 11. Thank you for your work, this is a very useful tool.

**Comment by wnabil** [comment]
Hi
you can use --force for now until i update it

**Comment by wnabil** [comment]
updated, 1.12.0+
