### ISSUE TITLE
how to add utf-8 encode when export csv

### ISSUE THREAD

**Issue by moeali1010** [wnabil/ngx-export-as#94]
how to add utf-8 encode when export cvs ?

**Comment by wnabil** [comment]
works as expected, please specify a test case
[myFile.csv](https://github.com/wnabil/ngx-export-as/files/6873985/myFile.csv)
![image](https://user-images.githubusercontent.com/23165327/126901518-9622935d-0418-4e66-ba58-694821b9433b.png)

**Comment by ankurkhunt** [comment]
I am also facing the same issue while viewing CSV in Microsoft excel.

<img width="803" alt="image" src="https://github.com/wnabil/ngx-export-as/assets/34331536/34b01936-3295-432c-bcfa-dcb0f3819369">
