### ISSUE TITLE
Add support for changing delimiter in CSV or support for double quoting data if it contains comma(,) in data

### ISSUE THREAD

**Issue by souradeep07** [wnabil/ngx-export-as#97]
Add support for changing delimiter in CSV or support for double quoting data if it contains comma(,) in data.

Below comma(,) should be configurable based on some configuration

https://github.com/wnabil/ngx-export-as/blob/26c42c579c64d6a35d70183966298a1f5a099766/projects/ngx-export-as/src/lib/export-as.service.ts#L203

**Comment by wnabil** [comment]
Thanks for the fix, use v 1.12.2
